/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package optimalinventorysystem;

import java.sql.Connection;
import Hash.HashPassword;
import MySQL.Connect;
import MySQL.CRUD;
import java.awt.HeadlessException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Ethan
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fullnameField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        fnLabel = new javax.swing.JLabel();
        pwLabel = new javax.swing.JLabel();
        unLabel = new javax.swing.JLabel();
        submitBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(7, 45, 46));

        jPanel1.setBackground(new java.awt.Color(7, 45, 46));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullnameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(fullnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 196, 309, 49));

        usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 293, 309, 49));

        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 309, 53));

        fnLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fnLabel.setForeground(new java.awt.Color(255, 255, 255));
        fnLabel.setText("Full Name");
        jPanel1.add(fnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 167, 146, 28));

        pwLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pwLabel.setForeground(new java.awt.Color(255, 255, 255));
        pwLabel.setText("Password");
        jPanel1.add(pwLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 360, 146, 28));

        unLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unLabel.setForeground(new java.awt.Color(255, 255, 255));
        unLabel.setText("Username");
        jPanel1.add(unLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 263, 146, 28));

        submitBtn.setBackground(new java.awt.Color(105, 240, 174));
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Submit");

        javax.swing.GroupLayout submitBtnLayout = new javax.swing.GroupLayout(submitBtn);
        submitBtn.setLayout(submitBtnLayout);
        submitBtnLayout.setHorizontalGroup(
            submitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        submitBtnLayout.setVerticalGroup(
            submitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 503, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Register");
        jLabel6.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 79, 309, 58));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
        String fullname = fullnameField.getText();
        String username = usernameField.getText();
        String password = String.valueOf(passwordField.getPassword());
        
        if("".equals(fullname))
            JOptionPane.showMessageDialog(null, "Full Name is required!");
        else if("".equals(username))
            JOptionPane.showMessageDialog(null, "Username is required!");
        else if("".equals(password))
            JOptionPane.showMessageDialog(null, "Password is required!");
        else{
            try{
                Connection con = Connect.getConnection();
                if(!CRUD.checkUserExists(con,username)){
                    if(password.length() >= 8){
                        password=HashPassword.hashPassword(password);
                        CRUD.insertUser(con,fullname,username,password,-1);
                        JOptionPane.showMessageDialog(null, "User has been successfully created!");
                    }else{
                        JOptionPane.showMessageDialog(null, "Password must contain at least 8 characters...");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Username already taken...");
                }
            }catch(HeadlessException | NoSuchAlgorithmException | SQLException e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_submitBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fnLabel;
    private javax.swing.JTextField fullnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel pwLabel;
    private javax.swing.JPanel submitBtn;
    private javax.swing.JLabel unLabel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
